general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:
    sequences:
      priority_level_1: []
    parallels:
       priority_level_1: []
    ss_drivetrain:
      priority_level_2: [st_drivetrain_zero]
      priority_level_1: [st_drivetrain_swerve_vector, st_drivetrain_swerve_math, st_drivetrain_swerve_matthew]
      default: []

  subsystems: [ss_drivetrain]

  input_booleans: [ipb_driver_back, ipb_driver_start, ipb_driver_a, ipb_driver_left_stick_button, ipb_driver_right_stick_button]

  input_numerics: [ipn_driver_left_y, ipn_driver_left_x, ipn_driver_right_y, ipn_driver_right_x,
                   ipn_drivetrain_front_right_angle, ipn_drivetrain_front_left_angle, ipn_drivetrain_back_left_angle, ipn_drivetrain_back_right_angle]

  input_vectors: [ipv_swerve_odometry, ipv_navx]

  output_numerics: [opn_drivetrain_front_right_speed, opn_drivetrain_front_left_speed, opn_drivetrain_back_left_speed, opn_drivetrain_back_right_speed, opn_drivetrain_front_right_angle, opn_drivetrain_front_left_angle, opn_drivetrain_back_left_angle, opn_drivetrain_back_right_angle]

  output_booleans: []

global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_drivetrain_swerve_math:
  x_left_js: ipn_driver_left_x
  y_left_js: ipn_driver_left_y
  x_right_js: ipn_driver_right_x
  y_right_js: ipn_driver_right_y
  robot_length: 36.0
  robot_width: 24.0
  navx: ipv_navx

global_drivetrain_swerve_vector:
  swerve_x: ipn_driver_left_x
  swerve_y: ipn_driver_left_y
  swerve_rotate: ipn_driver_right_x
  swerve_field_oriented_button: ipb_driver_start
  navx: ipv_navx
  # The robot is centered on the x,y axis with the front of the robot pointing towards 0 on the unit circle
  swerve_front_right_module_position: [ 30.0, -20.0 ]
  swerve_front_left_module_position: [ 30.0, 20.0 ]
  swerve_back_left_module_position: [ -30.0, 20.0 ]
  swerve_back_right_module_position: [ -30.0, -20.0 ]
  input_angle_names:  [ "ipn_drivetrain_front_right_angle", "ipn_drivetrain_front_left_angle", "ipn_drivetrain_back_left_angle", "ipn_drivetrain_back_right_angle"]
  input_speed_names:  [ "ipn_drivetrain_front_right_speed", "ipn_drivetrain_front_left_speed", "ipn_drivetrain_back_left_speed", "ipn_drivetrain_back_right_speed"]
  output_angle_names: [ "opn_drivetrain_front_right_angle", "opn_drivetrain_front_left_angle", "opn_drivetrain_back_left_angle", "opn_drivetrain_back_right_angle"]
  output_speed_names: [ "opn_drivetrain_front_right_speed", "opn_drivetrain_front_left_speed", "opn_drivetrain_back_left_speed", "opn_drivetrain_back_right_speed"]

global_drivetrain_Matthew:
  swerve_front_right_module_position: [ 30.0, -20.0 ]
  swerve_front_left_module_position: [ 30.0, 20.0 ]
  swerve_back_left_module_position: [ -30.0, 20.0 ]
  swerve_back_right_module_position: [ -30.0, -20.0 ]
  swerve_x: ipn_driver_left_x
  swerve_y: ipn_driver_left_y
  swerve_rotate: ipn_driver_right_x
  swerve_field_oriented_button: ipb_driver_start


log:
#  ips_selected_auto: true

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values:

